### PR TITLE
login screen Android 1.1.0

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Updated Login screen for upcoming release 1.1.0

### CODE REVIEW

**Comment by MariusBluem** [comment]
THX. Please keep in mind #8 :grin: @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Woops, just a sec...

**Comment by AndyScherzinger** [comment]
DONE!

**Comment by MariusBluem** [comment]
Perfect :muscle:

**Comment by MariusBluem** [comment]
...and for the screenshots same as for the app: there are no branches (currently). A Screenshot should be merged only if the version is already out, because maybe some resources depend on it :grin: 

This is reminding me to create branches :stuck_out_tongue_winking_eye: 

@AndyScherzinger

**Comment by AndyScherzinger** [comment]
Argh, now you got me... Let's call it a draw :stuck_out_tongue_closed_eyes:

**Comment by AndyScherzinger** [comment]
The version is out actually... but only on the Google Play beta channel and here https://download.nextcloud.com/android/

**Pull request merged**
