### PR TITLE
Android app release 1.2.0 (phone)

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Phone screenshots updated for the upcoming Android app release 1.2.0

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@AndyScherzinger @tobiasKaminsky @LukasReschke by the way, the screenshot order in the Play Store can be improved a bit. We should show the screens in this order:
1. grid view
2. list view
3. log in (only then, not as first ;)
4. sidebar
5. multiaccounts in sidebar
6. settings

At least one screenshot can be left out, and that is the one with the multiaccount settings. That is already covered by multiaccount in the sidebar.

**Comment by AndyScherzinger** [comment]
Sounds good to me! :+1:

**Comment by jancborchardt** [comment]
@AndyScherzinger could you change it to that, or who has permissions for that? :)

**Comment by MorrisJobke** [comment]
> @AndyScherzinger could you change it to that, or who has permissions for that? :)

I guess this is @LukasReschke

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky and me also :) - Will change it as soon as we release 1.2.0

**Comment by AndyScherzinger** [comment]
@jancborchardt what about the upload view?

**Comment by AndyScherzinger** [comment]
@jancborchardt DONE!

**Comment by jancborchardt** [comment]
@AndyScherzinger nice! For the tablet/landscape screenshots afterwards it would be cool to have the same order and remove that one unneeded screenshot. :)

**Comment by AndyScherzinger** [comment]
@jancborchardt Also done! But we need someone with a tablet like @MorrisJobke to do the screenshots since my emulator seems to just render things like a phone... :(

**Comment by MorrisJobke** [comment]
> @jancborchardt Also done! But we need someone with a tablet like @MorrisJobke to do the screenshots since my emulator seems to just render things like a phone... :(

Could I ask you to open an issue for this and where do I get the APK from? Can you also describe what to capture and what common files I should use?

**Comment by AndyScherzinger** [comment]
We do not have any common files yet.
@jancborchardt Is there something like this to have consistent screenshots throughout all clients/interfaces? This would make sense, e.g. having ~3 screenshot users on the demo server with one having a fixed set of files/folders/shared-folders to do screenshots in all apps.

**Comment by jancborchardt** [comment]
@AndyScherzinger we do have https://demo.nextcloud.com :) it’s done by @stp-ip so if you need anything in addition you could ask him.

**Comment by AndyScherzinger** [comment]
Well a set of files and folders / scenarios we want to showcase in the screenshots.

**Comment by tobiasKaminsky** [comment]
Would be cool, also for avatars.
Nothing against you Andy but the screenshots should not shown individual devs, I think.

**Comment by AndyScherzinger** [comment]
They shouldn't, no! That's my point with a fixed set of accounts and dummy data for screenshots across all clients. 
So totally agreeing with you! :+1:

**Comment by jancborchardt** [comment]
We could simply add the relevant accounts and avatars to demo.nextcloud.com – then we also do not need to censor anything _and_ we advertise the demo server. :)

**Comment by jancborchardt** [comment]
I’d say for demo purposes, have one account »Ada« and the existing »Test«.

**Comment by AndyScherzinger** [comment]
Sounds good, as for proper screenshots we should have 3 accounts, while two of them could be dummies without any files.

**Comment by jancborchardt** [comment]
»Ada«, »Doug« and »Susan«. :) @stp-ip can you create those users? Ada should have the same files as the test account (and can you remove the C example file and the impress file as that’s too much otherwise).

(Referencing Ada Lovelace, Doug Engelbart & Susan Kare)

**Comment by AndyScherzinger** [comment]
Awesome :+1:

**Comment by stp-ip** [comment]
We can discuss the actual implementation during Hackweek and see what makes sense in the short- and long-term.

**Pull request merged**
