### PR TITLE
Fix unaliged text in files_drop image

### PR DESCRIPTION
**Pull request by blizzz**
due to custom browser settings

@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks a lot nice 👍

**Comment by MorrisJobke** [comment]
cc @jospoortvliet for this updated screenshot :)

**Comment by jancborchardt** [comment]
Btw for the future I recommend zooming in or making the view smaller. The screenshot has a _lot_ of whitespace and to see the actual feature you have to lean forward. ;)

**Comment by jospoortvliet** [comment]
Amen to what @jancborchardt said...

Generally speaking, screenshots should be low resolution, something like 1280x720 or so.

**Pull request merged**
