### PR TITLE
Add screenshot for "files drop"

### PR DESCRIPTION
**Pull request by blizzz**
@jospoortvliet

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Awesome ;-)

**Comment by MorrisJobke** [comment]
Weird ... the text next to the logo is not aligned. Which browser did you use, @blizzz ?

cc @jancborchardt

**Comment by blizzz** [comment]
@MorrisJobke FF 47

**Comment by blizzz** [comment]
> Weird ... the text next to the logo is not aligned.

Did not catch my attention, thanks for seeing this. Probably due to some custom CSS on Firefox, with a a different profile it renders normally. Will redo.

**Comment by blizzz** [comment]
https://github.com/nextcloud/screenshots/pull/5

**Pull request merged**
