### PR TITLE
Android screenshots for 3.0

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Screenshots for app v3

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@jospoortvliet  :-)

**Review by jospoortvliet — APPROVED** [review]

**Comment by MorrisJobke** [comment]
In the 06_davdroid the grey overlay is too much to the top and overlays also the phone.

**Comment by tobiasKaminsky** [comment]
This was intended, it overlays / grays out everything but the important part.
You suggest to only gray out the screen parts?

**Comment by MorrisJobke** [comment]
But it grays out part of the phone and this looks ugly - please Check the image ;)

**Pull request merged**
