### PR TITLE
update login screen

### LINKED ISSUE #8: The example server address is misleading
In the login.png, it says above the text box: 
"Server address https://..."
And the example text is:
"nextcloud.com"

I don't think nextcloud.com domain is itself a Nextcloud provider, is it? If it isn't, then this screenshot may confuse users. They would probably complain that "I entered exactly the server address that was shown on the screenshot, but it didn't work."

I suggest we either leave it empty as before, or fill it with "https://MyNextCloudProvider.com" or something similar.

### PR DESCRIPTION
**Pull request by MorrisJobke**
@AndyScherzinger Is this okay?
- fixes #8 

cc @mabkenar @LukasReschke @mar1u5

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Perfect :)

**Comment by mabkenar** [comment]
Wow, you guys are fast! Keep up the great work!

**Comment by mabkenar** [comment]
Just to make sure, does it also work without https:// in the beginning of the server address? I didn't notice it at first.

**Comment by AndyScherzinger** [comment]
Yes it does, that leads to the app trying https first and then http.

**Comment by mabkenar** [comment]
Cool app then! But in case the server is set with http and NOT https, does it mean that the connection will always be unencrypted even for future file transfers? If yes, this should be either banned completely or it should be done via some very big red warnings to the user.

**Comment by AndyScherzinger** [comment]
Yes that's what it mean, so if http is chosen the client show exactly that a hint to the user as in unencrypted connection and an "unlocked icon".

**Pull request merged**
