### PR TITLE
update screenshots with english versions

### PR DESCRIPTION
**Pull request by jancborchardt**
Please check them out @mar1u5 @tchncs @MorrisJobke @jospoortvliet @nextcloud/designers  :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
(I also zoomed in a notch more again to make it simpler.)

**Comment by MariusBluem** [comment]
👍

**Comment by verymilan** [comment]
nice :)

**Comment by williambargentball** [comment]
Love the login

**Pull request merged**
